<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Lmc.Kafka</PackageId>
    <Version>4.1.0</Version>
    <RepositoryUrl>https://stash.int.lmc.cz/projects/ARCHI/repos/fkafka/browse</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Events.fs" />
    <Compile Include="Consumer.fs" />
    <Compile Include="Producer.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="1.0-beta2" />
    <PackageReference Include="FSharp.Data" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lmc.ServiceIdentification" Version="1.2.0" />
  </ItemGroup>

</Project>
